import fs from "fs";
import path from "path";

// Valkyrie Runtime Support
const ValkyrieRuntime = {
  print: console.log,
  assert: (condition, message) => {
    if (!condition) throw new Error(message || "Assertion failed");
  }
};

const CodeGenerator = {output: "", indentLevel: 0};
function initCodeGenerator() {
  const generator = {};
  generator.output = "";
  generator.indentLevel = 0;
  return generator;
}

function addIndent(generator) {
  const indent = "";
  const i = 0;
  while ((i < generator.indentLevel)) {
    indent = (indent + "  ");
    i = (i + 1);
  }
  return indent;
}

function write(generator, code) {
  generator.output = (generator.output + code);
  return generator;
}

function writeLine(generator, code) {
  const indent = addIndent(generator);
  generator.output = (((generator.output + indent) + code) + "\n");
  return generator;
}

function increaseIndent(generator) {
  generator.indentLevel = (generator.indentLevel + 1);
  return generator;
}

function decreaseIndent(generator) {
  if ((generator.indentLevel > 0)) {
    generator.indentLevel = (generator.indentLevel - 1);
  }
  return generator;
}

function generateProgram(generator, node) {
  writeLine(generator, "// Generated by Valkyrie Compiler");
  writeLine(generator, "");
  const i = 0;
  while ((i < node.statements.length)) {
    generateStatement(generator, node.statements[i]);
    i = (i + 1);
  }
  return generator;
}

function generateStatement(generator, node) {
  if ((node.type === "VariableDeclaration")) {
    generateVariableDeclaration(generator, node);
  } else {
    if ((node.type === "FunctionDeclaration")) {
      generateFunctionDeclaration(generator, node);
    } else {
      if ((node.type === "IfStatement")) {
        generateIfStatement(generator, node);
      } else {
        if ((node.type === "BlockStatement")) {
          generateBlockStatement(generator, node);
        } else {
          if ((node.type === "ExpressionStatement")) {
            generateExpressionStatement(generator, node);
          }
        }
      }
    }
  }
  return generator;
}

function generateVariableDeclaration(generator, node) {
  const code = (("let " + node.name) + " = ");
  write(generator, (addIndent(generator) + code));
  generateExpression(generator, node.initializer);
  writeLine(generator, ";");
  return generator;
}

function generateFunctionDeclaration(generator, node) {
  const code = (("function " + node.name) + "(");
  write(generator, (addIndent(generator) + code));
  const i = 0;
  while ((i < node.parameters.length)) {
    if ((i > 0)) {
      write(generator, ", ");
    }
    write(generator, node.parameters[i].name);
    i = (i + 1);
  }
  writeLine(generator, ") {");
  increaseIndent(generator);
  generateStatement(generator, node.body);
  decreaseIndent(generator);
  writeLine(generator, "}");
  writeLine(generator, "");
  return generator;
}

function generateIfStatement(generator, node) {
  write(generator, (addIndent(generator) + "if ("));
  generateExpression(generator, node.condition);
  writeLine(generator, ") {");
  increaseIndent(generator);
  generateStatement(generator, node.thenBranch);
  decreaseIndent(generator);
  if ((node.elseBranch.type !== "")) {
    if ((node.elseBranch.type === "IfStatement")) {
      write(generator, (addIndent(generator) + "} else "));
      generateIfStatement(generator, node.elseBranch);
    } else {
      writeLine(generator, "} else {");
      increaseIndent(generator);
      generateStatement(generator, node.elseBranch);
      decreaseIndent(generator);
      writeLine(generator, "}");
    }
  } else {
    writeLine(generator, "}");
  }
  return generator;
}

function generateBlockStatement(generator, node) {
  const i = 0;
  while ((i < node.statements.length)) {
    generateStatement(generator, node.statements[i]);
    i = (i + 1);
  }
  return generator;
}

function generateExpressionStatement(generator, node) {
  write(generator, addIndent(generator));
  generateExpression(generator, node.expression);
  writeLine(generator, ";");
  return generator;
}

function generateExpression(generator, node) {
  if ((node.type === "AssignmentExpression")) {
    generateAssignmentExpression(generator, node);
  } else {
    if ((node.type === "BinaryExpression")) {
      generateBinaryExpression(generator, node);
    } else {
      if ((node.type === "UnaryExpression")) {
        generateUnaryExpression(generator, node);
      } else {
        if ((node.type === "CallExpression")) {
          generateCallExpression(generator, node);
        } else {
          if ((node.type === "Identifier")) {
            generateIdentifier(generator, node);
          } else {
            if ((node.type === "NumberLiteral")) {
              generateNumberLiteral(generator, node);
            } else {
              if ((node.type === "StringLiteral")) {
                generateStringLiteral(generator, node);
              } else {
                if ((node.type === "BooleanLiteral")) {
                  generateBooleanLiteral(generator, node);
                }
              }
            }
          }
        }
      }
    }
  }
  return generator;
}

function generateAssignmentExpression(generator, node) {
  generateExpression(generator, node.left);
  write(generator, " = ");
  generateExpression(generator, node.right);
  return generator;
}

function generateBinaryExpression(generator, node) {
  write(generator, "(");
  generateExpression(generator, node.left);
  write(generator, ((" " + node.operator) + " "));
  generateExpression(generator, node.right);
  write(generator, ")");
  return generator;
}

function generateUnaryExpression(generator, node) {
  write(generator, node.operator);
  generateExpression(generator, node.operand);
  return generator;
}

function generateCallExpression(generator, node) {
  generateExpression(generator, node.callee);
  write(generator, "(");
  const i = 0;
  while ((i < node.arguments.length)) {
    if ((i > 0)) {
      write(generator, ", ");
    }
    generateExpression(generator, node.arguments[i]);
    i = (i + 1);
  }
  write(generator, ")");
  return generator;
}

function generateIdentifier(generator, node) {
  write(generator, node.name);
  return generator;
}

function generateNumberLiteral(generator, node) {
  write(generator, node.value);
  return generator;
}

function generateStringLiteral(generator, node) {
  write(generator, (("\"" + node.value) + "\""));
  return generator;
}

function generateBooleanLiteral(generator, node) {
  if (node.value) {
    write(generator, "true");
  } else {
    write(generator, "false");
  }
  return generator;
}

function generate(ast) {
  const generator = initCodeGenerator();
  generateProgram(generator, ast);
  return generator.output;
}


// ValkyrieCompiler 类
class ValkyrieCompiler {
  compile(source, options = {}) {
    const compiler = initCompiler(source);
    const result = compile(compiler);
    return { success: true, code: result, ast: compiler.ast, tokens: compiler.tokens };
  }
  
  compileFile(filePath, options = {}) {
    const source = fs.readFileSync(filePath, "utf8");
    return this.compile(source, options);
  }
  
  compileDirectory(dirPath, options = {}) {
    const results = [];
    const files = fs.readdirSync(dirPath);
    for (const file of files) {
      if (file.endsWith(".valkyrie")) {
        const filePath = path.join(dirPath, file);
        results.push(this.compileFile(filePath, options));
      }
    }
    return results;
  }
}

// 导出编译器实例
const compiler = new ValkyrieCompiler();
export { ValkyrieCompiler, compiler, generate };
